name: Automatyczne Budowanie

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'  # Co tydzień, o północy w niedzielę
  workflow_dispatch:  # Uruchomienie ręczne

jobs:
  build:
    runs-on: windows-latest  # Uruchomienie na systemie Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 pyinstaller pytest

      - name: Build .exe using pyinstaller
        run: |
          pyinstaller --onefile --noconsole project.py

      - name: Upload .exe to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: mytest-exe
          path: dist/mytest.exe
